### ISSUE TITLE
file Chart.js is missing

### ISSUE THREAD

**Issue by Siddhant-K-code** [BlackKnightZERO/COVID19App#1]
ERROR in src/app/tab1/tab1.page.ts:4:23 - error TS2307: Cannot find module 'chart.js'.
4 import { Chart } from 'chart.js';

**Comment by BlackKnightZERO** [comment]
on project's root directory(where package.json is located) :
open powershell run these 3 commands : 
npm install 
ionic build
ionic serve

**Comment by Siddhant-K-code** [comment]
during npm instal , getting this error :->

npm ERR! cb() never called!

**Comment by Siddhant-K-code** [comment]
Thanks for the help. Its Completed
